// The page's four SELECTs, run against the real schema in a real database.
// The requests go through worker.fetch(), so what is exercised is the SQL the
// Worker contains, not a copy of it.
//
// This is where the cross-repo risk sits. pkghaus/apt owns schema.sql and
// writes these tables; this Worker only reads them, with the two most fragile
// statements in the estate: a window expressed as `day IN (SELECT ... LIMIT ?)`
// and a SUITE_RANK CASE fragment generated by string interpolation. Neither is
// covered by a type system, and a mismatch surfaces as a bare 503.

import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import worker from "../src/worker.js";
import { d1 } from "./d1.js";

const SCHEMA = fileURLToPath(new URL("./schema.sql", import.meta.url));

function seeded() {
  const db = d1(SCHEMA);
  globalThis.caches = { default: { match: async () => undefined, put: async () => {} } };
  globalThis.fetch = async () => new Response("origin", { status: 418 });
  const dl = "INSERT INTO downloads (day,package,version,suite,arch,count) VALUES (?,?,?,?,?,?)";
  const hb = "INSERT INTO heartbeats (day,suite,count) VALUES (?,?,?)";
  // Deliberately out of release order and across several days, so ordering
  // and windowing have something to get wrong.
  db.exec(dl, "2026-08-20", "zola", "0.23.4-1", "unstable", "amd64", 5);
  db.exec(dl, "2026-08-21", "croc", "11.3.0-1~testing1", "testing", "arm64", 2);
  db.exec(dl, "2026-08-22", "croc", "11.3.0-1~haus13+1", "trixie", "amd64", 9);
  db.exec(hb, "2026-08-20", "unstable", 3);
  db.exec(hb, "2026-08-21", "testing", 4);
  db.exec(hb, "2026-08-22", "trixie", 7);
  return { env: { DB: db.binding }, ctx: { waitUntil: () => {} } };
}

async function json() {
  const h = seeded();
  const res = await worker.fetch(new Request("https://apt.pkg.haus/stats.json"), h.env, h.ctx);
  assert.equal(res.status, 200, "a 503 here means a query no longer matches the schema");
  return res.json();
}

test("every query the page runs matches the schema", async () => {
  const d = await json();
  for (const k of ["downloads_by_package", "downloads_by_suite", "downloads_by_day", "update_checks"]) {
    assert.ok(Array.isArray(d[k]), `${k} came back as an array`);
    assert.ok(d[k].length > 0, `${k} returned rows`);
  }
});

test("package totals sum across days and sort by volume", async () => {
  const d = await json();
  assert.deepEqual(d.downloads_by_package, [
    { package: "croc", downloads: 11 },
    { package: "zola", downloads: 5 },
  ]);
});

test("SUITE_RANK orders by release, not alphabetically", async () => {
  const d = await json();
  assert.deepEqual(d.downloads_by_suite.map((r) => r.suite), ["trixie", "testing", "unstable"],
    "alphabetical would be testing, trixie, unstable");
});

test("the windowed subquery returns whole days, newest first", async () => {
  const d = await json();
  assert.deepEqual(d.downloads_by_day.map((r) => r.day),
    ["2026-08-22", "2026-08-21", "2026-08-20"]);
  assert.deepEqual(d.update_checks.map((r) => r.day),
    ["2026-08-22", "2026-08-21", "2026-08-20"]);
});

test("the page renders from real rows without throwing", async () => {
  const h = seeded();
  const res = await worker.fetch(new Request("https://apt.pkg.haus/stats"), h.env, h.ctx);
  assert.equal(res.status, 200);
  const html = await res.text();
  assert.match(html, /croc/);
  assert.match(html, /stable \(trixie\)/, "the suite label survives into the page");
});

test("an empty database renders rather than 503ing", async () => {
  const db = d1(SCHEMA);
  globalThis.caches = { default: { match: async () => undefined, put: async () => {} } };
  const res = await worker.fetch(new Request("https://apt.pkg.haus/stats"),
    { DB: db.binding }, { waitUntil: () => {} });
  assert.equal(res.status, 200, "a brand new archive has no rows and must still have a page");
});
