// The page's four SELECTs, run against the real schema in a real database.
// The requests go through worker.fetch(), so what is exercised is the SQL the
// Worker contains, not a copy of it.
//
// This is where the cross-repo risk sits. pkghaus/apt owns schema.sql and
// writes these tables; this Worker only reads them, with the two most fragile
// statements in the estate: a window expressed as `day IN (SELECT ... LIMIT ?)`
// and a SUITE_RANK CASE fragment generated by string interpolation. Neither is
// covered by a type system, and a mismatch surfaces as a bare 503.

import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import worker from "../src/worker.js";
import { d1 } from "./d1.js";

const SCHEMA = fileURLToPath(new URL("./schema.sql", import.meta.url));

function seeded() {
  const db = d1(SCHEMA);
  globalThis.caches = { default: { match: async () => undefined, put: async () => {} } };
  globalThis.fetch = async () => new Response("origin", { status: 418 });
  const dl = "INSERT INTO downloads (day,package,version,suite,arch,count) VALUES (?,?,?,?,?,?)";
  const hb = "INSERT INTO heartbeats (day,suite,count) VALUES (?,?,?)";
  // Deliberately out of release order and across several days, so ordering
  // and windowing have something to get wrong.
  db.exec(dl, "2026-08-20", "zola", "0.23.4-1", "unstable", "amd64", 5);
  db.exec(dl, "2026-08-21", "croc", "11.3.0-1~testing1", "testing", "arm64", 2);
  db.exec(dl, "2026-08-22", "croc", "11.3.0-1~haus13+1", "trixie", "amd64", 9);
  db.exec(hb, "2026-08-20", "unstable", 3);
  db.exec(hb, "2026-08-21", "testing", 4);
  db.exec(hb, "2026-08-22", "trixie", 7);
  return { env: { DB: db.binding }, ctx: { waitUntil: () => {} }, db };
}

async function served(h) {
  const res = await worker.fetch(new Request("https://apt.pkg.haus/stats.json"), h.env, h.ctx);
  assert.equal(res.status, 200, "a 503 here means a query no longer matches the schema");
  return res.json();
}

async function json() {
  return served(seeded());
}

test("every query the page runs matches the schema", async () => {
  const d = await json();
  for (const k of ["downloads_by_package", "downloads_by_suite", "downloads_by_day", "update_checks"]) {
    assert.ok(Array.isArray(d[k]), `${k} came back as an array`);
    assert.ok(d[k].length > 0, `${k} returned rows`);
  }
});

test("package totals sum across days and sort by volume", async () => {
  const d = await json();
  assert.deepEqual(d.downloads_by_package, [
    { package: "croc", downloads: 11, version: "" },
    { package: "zola", downloads: 5, version: "" },
  ]);
});

// The reason this table exists. A package the archive serves but nobody has
// installed has no row in `downloads`, so before the inventory it was absent
// from the page entirely -- which reads as "not in the archive" rather than
// "not yet downloaded".
test("a package with no downloads is listed, at zero", async () => {
  const h = seeded();
  h.db.exec("INSERT INTO packages (package,version) VALUES (?,?)", "kudu", "0.3.0-1");
  const d = await served(h);
  const kudu = d.downloads_by_package.find((r) => r.package === "kudu");
  assert.ok(kudu, "kudu is in the inventory and must appear");
  assert.equal(kudu.downloads, 0);
  assert.equal(kudu.version, "0.3.0-1");
});

// The union, not a LEFT JOIN from the inventory. Retirement is a normal
// operation, the counters are all-time, and driving off the inventory alone
// would erase a retired package's history the moment it left the fleet.
test("a retired package keeps its downloads after leaving the inventory", async () => {
  const h = seeded();
  h.db.exec("INSERT INTO packages (package,version) VALUES (?,?)", "kudu", "0.3.0-1");
  // croc and zola have downloads and are deliberately NOT in the inventory.
  const d = await served(h);
  const names = d.downloads_by_package.map((r) => r.package);
  assert.ok(names.includes("croc"), "croc has 11 downloads and must not vanish");
  assert.ok(names.includes("zola"), "zola has 5 downloads and must not vanish");
  assert.deepEqual(names, ["croc", "zola", "kudu"],
    "ordering stays downloads-descending, then name");
});

// The HTML is what a person actually sees, and it is rendered from a different
// code path than /stats.json. `version` rides along in the row objects for the
// JSON consumers; it must not appear as a stray cell here.
test("the page renders a zero-download row and does not leak version", async () => {
  const h = seeded();
  h.db.exec("INSERT INTO packages (package,version) VALUES (?,?)", "kudu", "0.3.0-1");
  const res = await worker.fetch(new Request("https://apt.pkg.haus/stats"), h.env, h.ctx);
  assert.equal(res.status, 200);
  const html = await res.text();
  const seg = html.slice(html.indexOf("Downloads by package"), html.indexOf("Downloads by suite"));
  assert.match(seg, /<tr><td>kudu<\/td><td>0<\/td><\/tr>/, "kudu must render at zero");
  assert.doesNotMatch(seg, /0\.3\.0-1/, "version must not become a cell");
  assert.deepEqual(seg.match(/<th>[^<]*<\/th>/g), ["<th>package</th>", "<th>downloads</th>"],
    "the column set must not change");
});

// Deploy order must not matter: this Worker and the ingest step that fills the
// table ship from different repos.
test("a missing inventory falls back instead of failing the page", async () => {
  const h = seeded();
  h.db.exec("DROP TABLE packages");
  const d = await served(h);
  assert.deepEqual(d.downloads_by_package, [
    { package: "croc", downloads: 11, version: "" },
    { package: "zola", downloads: 5, version: "" },
  ]);
});

test("SUITE_RANK orders by release, not alphabetically", async () => {
  const d = await json();
  assert.deepEqual(d.downloads_by_suite.map((r) => r.suite), ["trixie", "testing", "unstable"],
    "alphabetical would be testing, trixie, unstable");
});

test("the windowed subquery returns whole days, newest first", async () => {
  const d = await json();
  assert.deepEqual(d.downloads_by_day.map((r) => r.day),
    ["2026-08-22", "2026-08-21", "2026-08-20"]);
  assert.deepEqual(d.update_checks.map((r) => r.day),
    ["2026-08-22", "2026-08-21", "2026-08-20"]);
});

test("the page renders from real rows without throwing", async () => {
  const h = seeded();
  const res = await worker.fetch(new Request("https://apt.pkg.haus/stats"), h.env, h.ctx);
  assert.equal(res.status, 200);
  const html = await res.text();
  assert.match(html, /croc/);
  assert.match(html, /stable \(trixie\)/, "the suite label survives into the page");
});

test("an empty database renders rather than 503ing", async () => {
  const db = d1(SCHEMA);
  globalThis.caches = { default: { match: async () => undefined, put: async () => {} } };
  const res = await worker.fetch(new Request("https://apt.pkg.haus/stats"),
    { DB: db.binding }, { waitUntil: () => {} });
  assert.equal(res.status, 200, "a brand new archive has no rows and must still have a page");
});
